# Generated by Django 5.0 on 2023-12-31 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desifnationc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomc', models.CharField(max_length=40)),
                ('prenomc', models.CharField(max_length=40)),
                ('adressec', models.CharField(max_length=100)),
                ('telc', models.IntegerField()),
                ('creditc', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('prenome', models.CharField(max_length=40)),
                ('adressee', models.CharField(max_length=100)),
                ('tele', models.IntegerField()),
                ('salairee', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomf', models.CharField(max_length=40)),
                ('prenomf', models.CharField(max_length=40)),
                ('adressef', models.CharField(max_length=100)),
                ('telf', models.IntegerField()),
                ('soldef', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('prix', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='gestionEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField(blank=True, null=True)),
                ('retenueS', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('demandeAvance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaireJ', models.FloatField(max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=500)),
                ('dateAchat', models.DateField()),
                ('qteA', models.IntegerField()),
                ('prixH', models.FloatField(max_length=20)),
                ('montantp', models.FloatField(max_length=20)),
                ('fournisseurA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.fournisseur')),
                ('produitA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datereg', models.DateField()),
                ('montantreg', models.FloatField(max_length=20)),
                ('achat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.achat')),
                ('fournisseurreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetr', models.DateField()),
                ('qtetr', models.IntegerField()),
                ('prixac', models.FloatField(max_length=20)),
                ('centre_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.centre')),
                ('produit_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtev', models.IntegerField()),
                ('dateVente', models.DateField()),
                ('prixv', models.FloatField(max_length=20)),
                ('montantv', models.FloatField(max_length=20)),
                ('clientv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.client')),
                ('produitv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.produit')),
            ],
        ),
        migrations.CreateModel(
            name='PaimentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datepv', models.DateField()),
                ('montantpv', models.FloatField(max_length=20)),
                ('clientv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.client')),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.vente')),
            ],
        ),
    ]
