# Generated by Django 5.0 on 2023-12-31 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='desifnationc',
            new_name='designationc',
        ),
    ]
