# Generated by Django 5.0 on 2024-01-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_desifnationc_centre_designationc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achat',
            old_name='dateAchat',
            new_name='DateA',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='dateVente',
            new_name='DateV',
        ),
    ]
