# Generated by Django 5.0 on 2024-01-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_dateachat_achat_datea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_en_stock', models.IntegerField()),
                ('produitS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.produit')),
            ],
        ),
    ]
