# Generated by Django 5.0 on 2024-01-01 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_produits_etatstock_produit_etatstock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatstock',
            name='date',
        ),
        migrations.AddField(
            model_name='etatstock',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.fournisseur'),
        ),
    ]
