# Generated by Django 5.0 on 2024-01-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_etatstock_date_etatstock_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatstock',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='etatstock',
            name='achat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.achat'),
            preserve_default=False,
        ),
    ]
