# Generated by Django 5.0 on 2024-01-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_etatstock_fournisseur_etatstock_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatstock',
            name='achat',
        ),
    ]
