# Generated by Django 5.0 on 2024-01-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_etatstock_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='identifiant',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pv', models.DateField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.centre')),
                ('employes', models.ManyToManyField(to='application.employe')),
                ('transferts', models.ManyToManyField(to='application.transfert')),
                ('ventes', models.ManyToManyField(to='application.vente')),
            ],
        ),
    ]
