# Generated by Django 5.0 on 2024-01-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_centre_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='identifiant',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
