# Generated by Django 5.0 on 2024-01-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_centre_identifiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='identifiant',
        ),
        migrations.RemoveField(
            model_name='paimentcredit',
            name='clientv',
        ),
        migrations.RemoveField(
            model_name='reglement',
            name='fournisseurreg',
        ),
    ]
