# Generated by Django 5.0 on 2024-01-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_centre_identifiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='identifiant',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
