# Generated by Django 5.0 on 2024-01-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_centre_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatstock',
            name='quantite_en_stock',
            field=models.IntegerField(default=0),
        ),
    ]
