# Generated by Django 5.0 on 2024-01-06 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_etatstock_quantite_en_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatStockCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_en_stock', models.IntegerField(default=0)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.centre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.produit')),
            ],
        ),
    ]
