# Generated by Django 5.0 on 2024-01-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_etatstockcentre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etatstockcentre',
            old_name='produit',
            new_name='produit_stocke',
        ),
        migrations.RenameField(
            model_name='etatstockcentre',
            old_name='quantite_en_stock',
            new_name='quantite_en_stock_centre',
        ),
    ]
