# Generated by Django 5.0 on 2024-01-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_rename_produit_etatstockcentre_produit_stocke_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vente',
            unique_together={('produitv', 'clientv', 'DateV')},
        ),
    ]
