# Generated by Django 5.0 on 2024-01-21 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_avancesalaire_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.centre'),
        ),
    ]
